# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 15:20
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181006_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=tinymce.models.HTMLField(),
        ),
    ]
